//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jpetroulesMIDTERM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jpetroulesMIDTERM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,&quot;Hydrogen&quot;,&quot;H&quot;
        ///2,&quot;Helium&quot;,&quot;He&quot;
        ///3,&quot;Lithium&quot;,&quot;Li&quot;
        ///4,&quot;Beryllium&quot;,&quot;Be&quot;
        ///5,&quot;Boron&quot;,&quot;B&quot;
        ///6,&quot;Carbon&quot;,&quot;C&quot;
        ///7,&quot;Nitrogen&quot;,&quot;N&quot;
        ///8,&quot;Oxygen&quot;,&quot;O&quot;
        ///9,&quot;Fluorine&quot;,&quot;F&quot;
        ///10,&quot;Neon&quot;,&quot;Ne&quot;
        ///11,&quot;Sodium&quot;,&quot;Na&quot;
        ///12,&quot;Magnesium&quot;,&quot;Mg&quot;
        ///13,&quot;Aluminium&quot;,&quot;Al&quot;
        ///14,&quot;Silicon&quot;,&quot;Si&quot;
        ///15,&quot;Phosphorus&quot;,&quot;P&quot;
        ///16,&quot;Sulfur&quot;,&quot;S&quot;
        ///17,&quot;Chlorine&quot;,&quot;Cl&quot;
        ///18,&quot;Argon&quot;,&quot;Ar&quot;
        ///19,&quot;Potassium&quot;,&quot;K&quot;
        ///20,&quot;Calcium&quot;,&quot;Ca&quot;
        ///21,&quot;Scandium&quot;,&quot;Sc&quot;
        ///22,&quot;Titanium&quot;,&quot;Ti&quot;
        ///23,&quot;Vanadium&quot;,&quot;V&quot;
        ///24,&quot;Chromium&quot;,&quot;Cr&quot;
        ///25,&quot;Manganese&quot;,&quot;Mn&quot;
        ///26,&quot;Iron&quot;,&quot;Fe&quot;
        ///27,&quot;Cobalt&quot;,&quot;Co&quot;
        ///28,&quot;Nickel&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nitroglycerin&quot;,&quot;C3H5N3O9&quot;,&quot;is an oily liquid explosive obtained by nitrating glycerol. It is used in the manufacturing of explosives such as dynamite.&quot;
        ///&quot;Hexanitrostilbene&quot;,&quot;C14H6N6O12&quot;,&quot;is a heat-resistant liquid explosive.&quot;
        ///&quot;Water&quot;,&quot;H2O&quot;,
        ///&quot;Methane&quot;,&quot;CH4&quot;,
        ///&quot;Moronic acid&quot;,&quot;C30H46O3&quot;,
        ///&quot;Diamond&quot;,&quot;C&quot;,&quot;is one of the hardest natural substances known.&quot;
        ///&quot;Sapphire&quot;,&quot;Al2O3&quot;,&quot;is one of the hardest natural substances known. Both a gem and a metal, its molecular structure is very strong and it is used to manufact [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string substances {
            get {
                return ResourceManager.GetString("substances", resourceCulture);
            }
        }
    }
}
