//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaakovsMine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YaakovsMine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alloys can only be created through metalworking and thus cannot be mined..
        /// </summary>
        internal static string AlloysOnlyCreatedMetalworking {
            get {
                return ResourceManager.GetString("AlloysOnlyCreatedMetalworking", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap boulder {
            get {
                object obj = ResourceManager.GetObject("boulder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHEAT MODE!.
        /// </summary>
        internal static string CheatMode {
            get {
                return ResourceManager.GetString("CheatMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coal.
        /// </summary>
        internal static string Coal {
            get {
                return ResourceManager.GetString("Coal", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap coal_rock {
            get {
                object obj = ResourceManager.GetObject("coal_rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copper.
        /// </summary>
        internal static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap copper_rock {
            get {
                object obj = ResourceManager.GetObject("copper_rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Densium.
        /// </summary>
        internal static string Densium {
            get {
                return ResourceManager.GetString("Densium", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap densium_rock {
            get {
                object obj = ResourceManager.GetObject("densium_rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been injured by falling rocks! For now, your mission is at an end, and you will be taken to the elven medics in their capital city of Eiraddinas for healing and recovery. But have no fear, for the gods will not let a legend pass before his time. Soon, you will be ready to continue your mission...
        ///
        ///Press enter to start a new game..
        /// </summary>
        internal static string EndingMessage {
            get {
                return ResourceManager.GetString("EndingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has not been initialized..
        /// </summary>
        internal static string GameNotInitialized {
            get {
                return ResourceManager.GetString("GameNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        internal static byte[] hurt {
            get {
                object obj = ResourceManager.GetObject("hurt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are the Dwarven engineer Gad Yaakov. There is much metalworking to be done, and you must travel into the mines to obtain as much ore as you can. You also have a chance to test the explosive chemical nitroglycerin in your mining excursion so that you may document its use the engineering book you are writing. Good luck!
        ///
        ///Press enter to continue..
        /// </summary>
        internal static string IntroductionMessage {
            get {
                return ResourceManager.GetString("IntroductionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap iron_rock {
            get {
                object obj = ResourceManager.GetObject("iron_rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap medical_crate {
            get {
                object obj = ResourceManager.GetObject("medical_crate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mine_background {
            get {
                object obj = ResourceManager.GetObject("mine_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mithril.
        /// </summary>
        internal static string Mithril {
            get {
                return ResourceManager.GetString("Mithril", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mithril_rock {
            get {
                object obj = ResourceManager.GetObject("mithril_rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] nitroglycerin {
            get {
                object obj = ResourceManager.GetObject("nitroglycerin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nitroglycerin_crate {
            get {
                object obj = ResourceManager.GetObject("nitroglycerin_crate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pickaxe {
            get {
                object obj = ResourceManager.GetObject("pickaxe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickaxe.
        /// </summary>
        internal static string PickaxeType {
            get {
                return ResourceManager.GetString("PickaxeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rocks of this type cannot exist..
        /// </summary>
        internal static string RockTypeCannotExist {
            get {
                return ResourceManager.GetString("RockTypeCannotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin.
        /// </summary>
        internal static string Tin {
            get {
                return ResourceManager.GetString("Tin", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tin_rock {
            get {
                object obj = ResourceManager.GetObject("tin_rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vials of nitroglycerin.
        /// </summary>
        internal static string VialsOfNitroglycerin {
            get {
                return ResourceManager.GetString("VialsOfNitroglycerin", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_left0 {
            get {
                object obj = ResourceManager.GetObject("yaakov_left0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_left1 {
            get {
                object obj = ResourceManager.GetObject("yaakov_left1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_left2 {
            get {
                object obj = ResourceManager.GetObject("yaakov_left2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_left3 {
            get {
                object obj = ResourceManager.GetObject("yaakov_left3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_left4 {
            get {
                object obj = ResourceManager.GetObject("yaakov_left4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_left5 {
            get {
                object obj = ResourceManager.GetObject("yaakov_left5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_right0 {
            get {
                object obj = ResourceManager.GetObject("yaakov_right0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_right1 {
            get {
                object obj = ResourceManager.GetObject("yaakov_right1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_right2 {
            get {
                object obj = ResourceManager.GetObject("yaakov_right2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_right3 {
            get {
                object obj = ResourceManager.GetObject("yaakov_right3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_right4 {
            get {
                object obj = ResourceManager.GetObject("yaakov_right4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap yaakov_right5 {
            get {
                object obj = ResourceManager.GetObject("yaakov_right5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaakov&apos;s Mine.
        /// </summary>
        internal static string YaakovsMine {
            get {
                return ResourceManager.GetString("YaakovsMine", resourceCulture);
            }
        }
    }
}
