<?php
// array of 'page' variables
$page["content"] = "";
$page["webmaster"] = "webmaster@foopal.com";
$page["footer"] = '<p><a href="mailto:clugenbeel@generationsdp.com">contact us</a></p>';

$page["heading"] = '<h1><a href="index.php" title="link to homepage">CS-340 Internet Programming</a></h1>';
$page["help"] = "help";
$page["highlighted"] = "";
// turn on sidebars 
$page["sidebar_left"] = "sidebar_left";
$page["sidebar_right"] = "sidebar_right";

// single variables
$motto = '<span style="font-style:italic;">"do or do not, there is no try - Yoda"</span>';

?>